import { Validators } from '@angular/forms'
export const MOI_PAYMENTS_FORMS_FIELDS_CONFIGS: any = {
  //-------------------------------------------------------------------
  '095': {
    key: '095',
    apiKey: 'Visa',
    title: 'Visa',
    applicationsTypes: {
      //-------------------------------------------
      '038': {
        key: '038',
        title: 'Family Visa',
        fieldsConfigs: [
          {
            key: 'sponsorId',
            title: 'Sponsor Id',
            translate: 'visaServices.sponsorId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'numberOfVisas',
            title: 'Number of Visas',
            translate: 'visaServices.numberOfVisas',
            type: 'number',
            required: true,
            default: '',
            validators: [],
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '039': {
        key: '039',
        title: 'Labor Visa',
        fieldsConfigs: [
          {
            key: 'sponsorId',
            title: 'Sponsor Id',
            translate: 'visaServices.sponsorId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'numberOfVisas',
            title: 'Number of Visas',
            translate: 'visaServices.numberOfVisas',
            type: 'number',
            required: true,
            default: '',
            validators: [],
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'visaType',
            title: 'Visa Type',
            translate: 'visaServices.visaType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
            select_combo_key: 'eGovVisaTypes',
          },
        ],
      },
      //-------------------------------------------
    },
  },
  //-------------------------------------------------------------------
  '092': {
    key: '092',
    apiKey: 'SaudiPassport',
    title: 'Saudi Passport',
    applicationsTypes: {
      //-------------------------------------------
      '035': {
        key: '035',
        title: 'Issue New Passport',
        fieldsConfigs: [
          {
            key: 'citizenId',
            title: 'Citizen Id',
            translate: 'saudiPassportServices.citizenId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'passportType',
            title: 'Passport Type',
            translate: 'saudiPassportServices.passportType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovPassportTypes',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'passportDuration',
            title: 'Passport Duration',
            translate: 'saudiPassportServices.passportDuration',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovSadadPassportDuration',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '036': {
        key: '036',
        title: 'Re-issue Passport',
        fieldsConfigs: [
          {
            key: 'citizenId',
            title: 'Citizen Id',
            translate: 'saudiPassportServices.citizenId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'passportType',
            title: 'Passport Type',
            translate: 'saudiPassportServices.passportType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovPassportTypes',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'passportDuration',
            title: 'Passport Duration',
            translate: 'saudiPassportServices.passportDuration',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '037': {
        key: '037',
        title: 'Renew Passport',
        fieldsConfigs: [
          {
            key: 'citizenId',
            title: 'Citizen Id',
            translate: 'saudiPassportServices.citizenId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'passportType',
            title: 'Passport Type',
            translate: 'saudiPassportServices.passportType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovPassportTypes',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'passportDuration',
            title: 'Passport Duration',
            translate: 'saudiPassportServices.passportDuration',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovSadadPassportDuration',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
    },
  },
  //-------------------------------------------------------------------
  '091': {
    key: '091',
    apiKey: 'DrivingLicense',
    title: 'Driving License',
    applicationsTypes: {
      //-------------------------------------------
      '022': {
        key: '022',
        title: 'Issue License',
        fieldsConfigs: [
          {
            key: 'beneficiaryId',
            title: 'Beneficiary ID',
            translate: 'drivingLicenseServices.beneficiaryId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'licenseType',
            title: 'License Type',
            translate: 'drivingLicenseServices.licenseType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovLicenseTypeApp',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'licenseDuration',
            title: 'License Duration',
            translate: 'drivingLicenseServices.licenseDuration',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovLicenseDurationApp',
            select_dependent: true,
            select_parent: 'licenseType',
            select_combo_key_by_parent_value:
              'eGovLicenseDurationType[%value0%]',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '023': {
        key: '023',
        title: 'Issue License from Old License',
        fieldsConfigs: [
          {
            key: 'beneficiaryId',
            title: 'Beneficiary ID',
            translate: 'drivingLicenseServices.beneficiaryId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'licenseType',
            title: 'License Type',
            translate: 'drivingLicenseServices.licenseType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovLicenseTypeApp',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'licenseDuration',
            title: 'License Duration',
            translate: 'drivingLicenseServices.licenseDuration',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovLicenseDurationApp',
            select_dependent: true,
            select_parent: 'licenseType',
            select_combo_key_by_parent_value:
              'eGovLicenseDurationType[%value0%]',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '024': {
        key: '024',
        title: 'Replace License',
        fieldsConfigs: [
          {
            key: 'beneficiaryId',
            title: 'Beneficiary ID',
            translate: 'drivingLicenseServices.beneficiaryId',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'licenseType',
            title: 'License Type',
            translate: 'drivingLicenseServices.licenseType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovLicenseTypeApp',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'licenseDuration',
            title: 'License Duration',
            translate: 'drivingLicenseServices.licenseDuration',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovLicenseDurationApp',
            select_dependent: true,
            select_parent: 'licenseType',
            select_combo_key_by_parent_value:
              'eGovLicenseDurationType[%value0%]',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '025': {
        key: '025',
        title: 'Renew License',
        fieldsConfigs: [
          {
            key: 'beneficiaryId',
            title: 'Beneficiary ID',
            translate: 'drivingLicenseServices.beneficiaryId',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'licenseType',
            title: 'License Type',
            translate: 'drivingLicenseServices.licenseType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovLicenseTypeApp',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'licenseDuration',
            title: 'License Duration',
            translate: 'drivingLicenseServices.licenseDuration',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovLicenseDurationApp',
            select_dependent: true,
            select_parent: 'licenseType',
            select_combo_key_by_parent_value:
              'eGovLicenseDurationType[%value0%]',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
    },
  },
  //-------------------------------------------------------------------
  '096': {
    key: '096',
    apiKey: 'CivilRegistration',
    title: 'Civil Registration',
    applicationsTypes: {
      //-------------------------------------------
      '017': {
        key: '017',
        title: 'Birth Registration',
        fieldsConfigs: [
          {
            key: 'nationalIdNumber',
            title: 'National Id Number',
            translate: 'civilRegistrationServices.nationalIdNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'birthDate',
            title: 'Birth Date',
            translate: 'civilRegistrationServices.birthDate',
            type: 'date',
            required: true,
            default: '',
            validators: [],
            widget: 'datepicker-ar',
            widget_datepicker_min_date: false,
            widget_datepicker_max_date: true,
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'issuanceReason',
            title: 'Issuance Reasons',
            translate: 'civilDefenseViolationsServices.issuanceReason',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'cardVersionNumber',
            title: 'Card Version Number',
            translate: 'civilDefenseViolationsServices.cardVersionNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [Validators.maxLength(2)],
            maxlength: 2,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '018': {
        key: '018',
        title: 'Death Registration',
        fieldsConfigs: [
          {
            key: 'nationalIdNumber',
            title: 'National Id Number',
            translate: 'civilRegistrationServices.nationalIdNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'deathDate',
            title: 'Death Date',
            translate: 'civilRegistrationServices.deathDate',
            type: 'date',
            required: true,
            default: '',
            validators: [],
            widget: 'datepicker-ar',
            widget_datepicker_min_date: false,
            widget_datepicker_max_date: true,
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'issuanceReason',
            title: 'Issuance Reasons',
            translate: 'civilDefenseViolationsServices.issuanceReason',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'cardVersionNumber',
            title: 'Card Version Number',
            translate: 'civilDefenseViolationsServices.cardVersionNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [Validators.maxLength(2)],
            maxlength: 2,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '019': {
        key: '019',
        title: 'Marriage Registration',
        fieldsConfigs: [
          {
            key: 'nationalIdNumber',
            title: 'National Id Number',
            translate: 'civilRegistrationServices.nationalIdNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'marriageDate',
            title: 'Marriage Date',
            translate: 'civilRegistrationServices.marriageDate',
            type: 'date',
            required: true,
            default: '',
            validators: [],
            widget: 'datepicker-ar',
            widget_datepicker_min_date: false,
            widget_datepicker_max_date: true,
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'issuanceReason',
            title: 'Issuance Reasons',
            translate: 'civilDefenseViolationsServices.issuanceReason',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'cardVersionNumber',
            title: 'Card Version Number',
            translate: 'civilDefenseViolationsServices.cardVersionNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [Validators.maxLength(2)],
            maxlength: 2,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '020': {
        key: '020',
        title: 'Divorce Registration',
        fieldsConfigs: [
          {
            key: 'nationalIdNumber',
            title: 'National Id Number',
            translate: 'civilRegistrationServices.nationalIdNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'divorceDate',
            title: 'Divorce Date',
            translate: 'civilRegistrationServices.divorceDate',
            type: 'date',
            required: true,
            default: '',
            validators: [],
            widget: 'datepicker-ar',
            widget_datepicker_min_date: false,
            widget_datepicker_max_date: true,
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'issuanceReason',
            title: 'Issuance Reasons',
            translate: 'civilDefenseViolationsServices.issuanceReason',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'cardVersionNumber',
            title: 'Card Version Number',
            translate: 'civilDefenseViolationsServices.cardVersionNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [Validators.maxLength(2)],
            maxlength: 2,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '021': {
        key: '021',
        title: 'Issue ID Card',
        fieldsConfigs: [
          {
            key: 'nationalIdNumber',
            title: 'National Id Number',
            translate: 'civilDefenseViolationsServices.nationalIdNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'issuanceReason',
            title: 'Issuance Reasons',
            translate: 'civilDefenseViolationsServices.issuanceReason',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovSadadIssuanceReason',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'cardVersionNumber',
            title: 'Card Version Number',
            translate: 'civilDefenseViolationsServices.cardVersionNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(2)],
            maxlength: 2,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '053': {
        key: '053',
        title: 'Issue Family Card',
        fieldsConfigs: [
          {
            key: 'nationalIdNumber',
            title: 'National Id Number',
            translate: 'civilDefenseViolationsServices.nationalIdNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'issuanceReason',
            title: 'Issuance Reasons',
            translate: 'civilDefenseViolationsServices.issuanceReason',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovSadadIssuanceReason',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'cardVersionNumber',
            title: 'Card Version Number',
            translate: 'civilDefenseViolationsServices.cardVersionNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(2)],
            maxlength: 2,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '054': {
        key: '054',
        title: 'Other Fees and Fines',
        fieldsConfigs: [
          {
            key: 'nationalIdNumber',
            title: 'National Id Number',
            translate: 'civilDefenseViolationsServices.nationalIdNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'issuanceReason',
            title: 'Issuance Reasons',
            translate: 'civilDefenseViolationsServices.issuanceReason',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'cardVersionNumber',
            title: 'Card Version Number',
            translate: 'civilDefenseViolationsServices.cardVersionNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [Validators.maxLength(2)],
            maxlength: 2,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
    },
  },
  //-------------------------------------------------------------------
  '158': {
    key: '158',
    apiKey: 'CivilDefenseViolations',
    title: 'Civil Defense',
    applicationsTypes: {
      //-------------------------------------------
      '055': {
        key: '055',
        title: 'Pay All Civil Defense Violations fines',
        fieldsConfigs: [
          {
            key: 'violatorId',
            title: 'Violator Id',
            translate: 'civilDefenseViolationsServices.violatorId',
            type: 'text',
            required: true,
            default: '',
            validators: [],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'verdictNumber',
            title: 'Verdict Number',
            translate: 'trafficViolationsServices.verdictNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '056': {
        key: '056',
        title: 'Pay One Civil Defense Violations fines',
        fieldsConfigs: [
          {
            key: 'violatorId',
            title: 'Violator Id',
            translate: 'civilDefenseViolationsServices.violatorId',
            type: 'text',
            required: true,
            default: '',
            validators: [],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'verdictNumber',
            title: 'Verdict Number',
            translate: 'trafficViolationsServices.verdictNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
    },
  },
  //-------------------------------------------------------------------
  '090': {
    key: '090',
    apiKey: 'AlienControl',
    title: 'Expatriate Services',
    applicationsTypes: {
      //-------------------------------------------
      '001': {
        key: '001',
        title: 'Extend Visitor Visa',
        fieldsConfigs: [
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.minLength(10), Validators.maxLength(10)],
            minlength: 10,
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '002': {
        key: '002',
        title: 'Issue New Iqama',
        fieldsConfigs: [
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'iqamaDuration',
            title: 'Iqama Duration',
            translate: 'expatriateServices.iqamaDuration',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovSadadIqamaDuration', // "eGovSadadVisaDuration",
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'sponsorId',
            title: 'Sponsor Id',
            translate: 'expatriateServices.sponsorId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'jobCategory',
            title: 'Job Category',
            translate: 'expatriateServices.jobCategory',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovSadadJobCategory',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '003': {
        key: '003',
        title: 'Renew Iqama',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama Id',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'iqamaDuration',
            title: 'Iqama Duration',
            translate: 'expatriateServices.iqamaDuration',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovSadadIqamaDuration',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            maxlength: 10,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '004': {
        key: '004',
        title: 'Exit Re-entry Visa (Single)',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama Id',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'visaDuration',
            title: 'Iqama Duration',
            translate: 'expatriateServices.visaDuration',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovSadadVisaDuration',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            maxlength: 10,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '005': {
        key: '005',
        title: 'Exit Re-entry Visa(Multiple)',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama Id',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'visaDuration',
            title: 'Iqama Duration',
            translate: 'expatriateServices.visaDuration',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovSadadVisaDuration',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            maxlength: 10,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '006': {
        key: '006',
        title: 'Visa Cancellation',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama Id',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'visaNumber',
            title: 'Visa Number',
            translate: 'expatriateServices.visaNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            maxlength: 10,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '007': {
        key: '007',
        title: 'Transfer of Sponsorship',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama Id',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            maxlength: 10,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '008': {
        key: '008',
        title: 'Replace Iqama',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama Id',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            maxlength: 10,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '009': {
        key: '009',
        title: 'Transfer Dependant to be Head of Household',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama Id',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'iqamaDuration',
            title: 'Iqama Duration',
            translate: 'expatriateServices.iqamaDuration',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovSadadIqamaDuration',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'sponsorId',
            title: 'Sponsor Id',
            translate: 'expatriateServices.sponsorId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'jobCategory',
            title: 'Job Category',
            translate: 'expatriateServices.jobCategory',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovSadadJobCategory',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            maxlength: 10,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '010': {
        key: '010',
        title: 'Transfer Head of Household to be Dependant',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama Id',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '011': {
        key: '011',
        title: 'Transfer Dependant to a New Head of Household',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama Id',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '012': {
        key: '012',
        title: 'Change of Occupation',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama Id',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '013': {
        key: '013',
        title: 'Dependents Entry visa Fee Collection',
        translate: 'Dependents Entry visa Fee Collection',
        fieldsConfigs: [
          {
            key: 'householdIdNumber',
            title: 'House Hold Id Number',
            translate: 'expatriateServices.householdIdNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'numberDependant',
            title: 'Number Dependent',
            translate: 'expatriateServices.numberDependant',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '014': {
        key: '014',
        title:
          'Adding Dependent born inside Saudi Arabia after one Year from his Date of Birth',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama Id',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'dependantHijriBirthDate',
            title: 'Birth Date',
            translate: 'expatriateServices.dependantHijriBirthDate',
            type: 'date',
            required: true,
            default: '',
            validators: [],
            widget: 'datepicker-ar',
            widget_datepicker_min_date: false,
            widget_datepicker_max_date: false,
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [Validators.pattern('[0123456789]*')],
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '015': {
        key: '015',
        title: 'Dependent Separation',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama Id',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [Validators.pattern('[0123456789]*')],
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '016': {
        key: '016',
        title: 'Issue New Iqama for a Citizens Wife',
        fieldsConfigs: [
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'citizenId',
            title: 'Citizen ID',
            translate: 'expatriateServices.citizenId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'iqamaDuration',
            title: 'Iqama Duration',
            translate: 'expatriateServices.iqamaDuration',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovSadadIqamaDuration',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '057': {
        key: '057',
        title: 'Extend Exit Re-Entry Visa Duration',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama Id',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'visaNumber',
            title: 'Visa Number',
            translate: 'expatriateServices.visaNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'visaDuration',
            title: 'Visa Duration',
            translate: 'expatriateServices.visaDuration',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovSadadVisaDuration',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            maxlength: 10,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '052': {
        key: '052',
        title: 'Lost Passport Fine',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama Id',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            maxlength: 10,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '058': {
        key: '058',
        title: 'Associate Fees for a Specific Associate',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama ID / Border Number',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'associatedBorderNumber',
            title: 'Associate Iqama ID / Associate Border Number',
            translate: 'expatriateServices.associateIqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'feesDurationEndDate',
            title: 'Fees Duration End',
            translate: 'expatriateServices.feesDurationEndDate',
            type: 'date',
            required: true,
            default: '',
            validators: [],
            widget: 'datepicker-ar',
            widget_datepicker_min_date: true,
            widget_datepicker_max_date: false,
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '059': {
        key: '059',
        title:
          'Associate Fees for All Registered Associates on the Head of Household Iqama',
        fieldsConfigs: [
          {
            key: 'iqamaId',
            title: 'Iqama ID / Border Number',
            translate: 'expatriateServices.iqamaId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            minlength: 10,
            maxlength: 10,
            inputPattern: 'onlyDigits',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'feesDurationEndDate',
            title: 'Fees Duration End',
            translate: 'expatriateServices.feesDurationEndDate',
            type: 'date',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: 'datepicker-ar',
            widget_datepicker_min_date: true,
            widget_datepicker_max_date: false,
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'borderNumber',
            title: 'Border Number',
            translate: 'expatriateServices.borderNumber',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
    },
  },
  //-------------------------------------------------------------------
  '094': {
    key: '094',
    apiKey: 'MotorVehicles',
    title: 'Motor Vehicles',
    applicationsTypes: {
      //-------------------------------------------
      '026': {
        key: '026',
        title: 'Renew Vehicle Registration',
        fieldsConfigs: [
          {
            key: 'currentOwnerId',
            title: 'Current Owner Id',
            translate: 'motorVehiclesServices.currentOwnerId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleSequenceNumber',
            title: 'Vehicle Sequence Number',
            translate: 'motorVehiclesServices.vehicleSequenceNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(9)],
            maxlength: 9,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          }
        ],
      },
      //-------------------------------------------
      '027': {
        key: '027',
        title: 'Transfer Owner',
        fieldsConfigs: [
          {
            key: 'currentOwnerId',
            title: 'Current Owner Id',
            translate: 'motorVehiclesServices.currentOwnerId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleSequenceNumber',
            title: 'Vehicle Sequence Number',
            translate: 'motorVehiclesServices.vehicleSequenceNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'newOwnerId',
            title: 'New Owner Id',
            translate: 'motorVehiclesServices.newOwnerId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '028': {
        key: '028',
        title: 'Re-issue Registration Card',
        fieldsConfigs: [
          {
            key: 'currentOwnerId',
            title: 'Current Owner Id',
            translate: 'motorVehiclesServices.currentOwnerId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleSequenceNumber',
            title: 'Vehicle Sequence Number',
            translate: 'motorVehiclesServices.vehicleSequenceNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'reason',
            title: 'Card Issuance Reason',
            translate: 'motorVehiclesServices.cardIssuanceReason',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovVehicleCardRegisterationReason',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '029': {
        key: '029',
        title: 'Re-issue License Plate',
        fieldsConfigs: [
          {
            key: 'currentOwnerId',
            title: 'Current Owner Id',
            translate: 'motorVehiclesServices.currentOwnerId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleSequenceNumber',
            title: 'Vehicle Sequence Number',
            translate: 'motorVehiclesServices.vehicleSequenceNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'reason',
            title: 'Plate Issuance Reason',
            translate: 'motorVehiclesServices.plateIssuanceReason',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovPlateIssuanceReason',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'licensePlateWithLogo',
            title: 'License Plate WithLogo',
            translate: 'motorVehiclesServices.licensePlateWithLogo',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovLicensePlatewithLogo',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-6',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '030': {
        key: '030',
        title: 'Export Vehicle',
        fieldsConfigs: [
          {
            key: 'currentOwnerId',
            title: 'Current Owner Id',
            translate: 'motorVehiclesServices.currentOwnerId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleSequenceNumber',
            title: 'Vehicle Sequence Number',
            translate: 'motorVehiclesServices.vehicleSequenceNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '031': {
        key: '031',
        title: 'Exchange Plates',
        fieldsConfigs: [
          {
            key: 'currentOwnerId',
            title: 'Current Owner Id',
            translate: 'motorVehiclesServices.currentOwnerId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleSequenceNumber',
            title: 'Vehicle Sequence Number',
            translate: 'motorVehiclesServices.vehicleSequenceNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '032': {
        key: '032',
        title: 'Exchange Plates Not by Owner',
        fieldsConfigs: [
          {
            key: 'currentOwnerId',
            title: 'Current Owner Id',
            translate: 'motorVehiclesServices.currentOwnerId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleSequenceNumber',
            title: 'Vehicle Sequence Number',
            translate: 'motorVehiclesServices.vehicleSequenceNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(9)],
            maxlength: 9,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'newOwnerId',
            title: 'New Owner Id',
            translate: 'motorVehiclesServices.newOwnerId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '044': {
        key: '044',
        title:
          'Transfer Plates (Give plates to registered vehicle without plates)',
        fieldsConfigs: [
          {
            key: 'currentOwnerId',
            title: 'Current Owner Id',
            translate: 'motorVehiclesServices.currentOwnerId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleSequenceNumber',
            title: 'Vehicle Sequence Number',
            translate: 'motorVehiclesServices.vehicleSequenceNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(9)],
            maxlength: 9,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'newVehicleRegistrationType',
            title: 'New Vehicle Registration Type',
            translate: 'motorVehiclesServices.newVehicleRegistrationType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovVehicleRegistrationType',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleBodyType',
            title: 'Vehicle Body Type',
            translate: 'motorVehiclesServices.vehicleBodyType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovVehicleBodyType',
            select_dependent: true,
            select_parent: 'newVehicleRegistrationType',
            select_combo_key_by_parent_value: 'eGovVehicleBodyType[%value0%]',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '045': {
        key: '045',
        title: 'Transfer Plates (Changing Current Vehicle plate)',
        fieldsConfigs: [
          {
            key: 'currentOwnerId',
            title: 'Current Owner Id',
            translate: 'motorVehiclesServices.currentOwnerId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleSequenceNumber',
            title: 'Vehicle Sequence Number',
            translate: 'motorVehiclesServices.vehicleSequenceNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(9)],
            maxlength: 9,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'newVehicleRegistrationType',
            title: 'New Vehicle Registration Type',
            translate: 'motorVehiclesServices.newVehicleRegistrationType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovVehicleRegistrationType',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleBodyType',
            title: 'Vehicle Body Type',
            translate: 'motorVehiclesServices.vehicleBodyType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovVehicleBodyType',
            select_dependent: true,
            select_parent: 'newVehicleRegistrationType',
            select_combo_key_by_parent_value: 'eGovVehicleBodyType[%value0%]',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '042': {
        key: '042',
        title: 'Register Vehicle',
        fieldsConfigs: [
          {
            key: 'newOwnerId',
            title: 'New Owner Id',
            translate: 'motorVehiclesServices.newOwnerId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleCustomCardNumber',
            title: 'Vehicle Custom Card Number',
            translate: 'motorVehiclesServices.vehicleCustomCardNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'newVehicleRegistrationType',
            title: 'New Vehicle Registration Type',
            translate: 'motorVehiclesServices.newVehicleRegistrationType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovVehicleRegistrationType',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleBodyType',
            title: 'Vehicle Body Type',
            translate: 'motorVehiclesServices.vehicleBodyType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovVehicleBodyType',
            select_dependent: true,
            select_parent: 'newVehicleRegistrationType',
            select_combo_key_by_parent_value: 'eGovVehicleBodyType[%value0%]',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'licensePlateWithLogo',
            title: 'License Plate WithLogo',
            translate: 'motorVehiclesServices.licensePlateWithLogo',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovLicensePlatewithLogo',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-6',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '043': {
        key: '043',
        title: 'Re-import-Vehicle',
        fieldsConfigs: [
          {
            key: 'newOwnerId',
            title: 'New Owner Id',
            translate: 'motorVehiclesServices.newOwnerId',
            type: 'text',
            required: true,
            default: '',
            validators: [
              Validators.minLength(10),
              Validators.maxLength(10),
              Validators.pattern('[0123456789]*'),
            ],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleCustomCardNumber',
            title: 'Vehicle Custom Card Number',
            translate: 'motorVehiclesServices.vehicleCustomCardNumber',
            type: 'text',
            required: true,
            default: '',
            validators: [Validators.maxLength(10)],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'newVehicleRegistrationType',
            title: 'New Vehicle Registration Type',
            translate: 'motorVehiclesServices.newVehicleRegistrationType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovVehicleRegistrationType',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'vehicleBodyType',
            title: 'Vehicle Body Type',
            translate: 'motorVehiclesServices.vehicleBodyType',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovVehicleBodyType',
            select_dependent: true,
            select_parent: 'newVehicleRegistrationType',
            select_combo_key_by_parent_value: 'eGovVehicleBodyType[%value0%]',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
    },
  },
  //-------------------------------------------------------------------
  '093': {
    key: '093',
    apiKey: 'TrafficViolations',
    title: 'Traffic Violations',
    applicationsTypes: {
      //-------------------------------------------
      '040': {
        key: '040',
        title: 'Query Violations By Civilian Id',
        fieldsConfigs: [
          {
            key: 'violatorId',
            title: 'Violator Id',
            translate: 'trafficViolationsServices.violatorId',
            type: 'text',
            required: true,
            default: '',
            validators: [],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          // todo no son necesarios, pero el API los requiere, los ponemos hidden
          {
            key: 'violationId',
            title: 'Violation Id',
            translate: 'trafficViolationsServices.violationId',
            type: 'hidden',
            required: false,
            default: '0000000000',
            validators: [],
            widget: '',
            widget_container_class: 'hidden',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
      '041': {
        key: '041',
        title: 'Query Traffic Violation',
        fieldsConfigs: [
          {
            key: 'violationId',
            title: 'Violation Id',
            translate: 'trafficViolationsServices.violationId',
            type: 'text',
            required: true,
            default: '',
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'violatorId',
            title: 'Violator Id',
            translate: 'trafficViolationsServices.violatorId',
            type: 'text',
            required: true,
            default: '',
            validators: [],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-3',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
      //-------------------------------------------
    },
  },
  //-------------------------------------------------------------------
  '126': {
    key: '126',
    apiKey: 'PublicViolation',
    title: 'Public Violation',
    applicationsTypes: {
      //-------------------------------------------
      '060': {
        key: '060',
        title: 'Pay by Violator ID for a Specific Category',
        fieldsConfigs: [
          {
            key: 'violatorId',
            title: 'Violator Id',
            translate: 'publicViolation.violatorId',
            type: 'text',
            required: true,
            default: '',
            validators: [],
            maxlength: 10,
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-4',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'issuingEntity',
            title: 'Issuing Entity',
            translate: 'publicViolation.issuingEntity',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovViolationsIssuingEntity',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-8',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
          {
            key: 'category',
            title: 'Category',
            translate: 'publicViolation.category',
            type: 'select',
            required: true,
            default: '',
            validators: [],
            select_combo_key: 'eGovCategory',
            select_dependent: true,
            select_parent: 'issuingEntity',
            select_combo_key_by_parent_value: 'eGovCategory[%value0%]',
            widget: '',
            widget_container_class: 'col-xs-12 col-sm-8',
            widget_container_init_row: false,
            widget_container_end_row: false,
          },
        ],
      },
    },
  },
}
