version: '2'
services:
  web:
    image: angular2-luis/test
    ports:
      - 4200:4200
    networks:
      - front-tier
    volumes:
      - DEST:/usr/src/app
  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - web
    networks:
      - front-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

networks:
  front-tier:
    driver: bridge

