export interface BulkPaymentFees {
  activeFlag: string
  bulkPaymentsDebitAccount: string
  bulkPaymentsPrivilege: string
  chargeAccountFixed: string
  chargeAccountNumber: string
  combined: string
  combinedDaysFeedbackFlag: 0
  combinedFeedbackFlag: string
  combinedSum: string
  companyCat: string
  companyCode: string
  companyName: string
  companyUpdateDateAndTime: string
  confirmation: string
  confirmationFeedbackFlag: string
  currencyCode: string
  currencyDebitAccount: string
  debitPreference: string
  errorMessageKey: string
  feedbackType: string
  fileFee: 0
  forceDebitOrFundFlag: string
  functionToBePerformed: string
  generationDate: 0
  initial: string
  initialFeedbackFlag: string
  monthlyFee: 0
  monthlyFeesFlag: string
  organizationType: string
  penaltyFee: 0
  postingFlag: string
  productChannelCode: string
  productCode: string
  profileNumber: string
  registered: true
  reject: string
  rejected: string
  rejectionFeedbackFlag: string
  requestType: string
  statusFlag: string
  summaryReportCombinedFeedback: string
  summaryReportRejectionFeedback: string
  systemDate: string
  transactionCanFee: 0
  transactionCanFeeLocal: 0
  transactionFailFee: 0
  transactionFailFeeLocal: 0
  transactionFee: 0
  transactionFeeCurrentLocal: 0
  transactionFeeLocal: 0
  updateOnlyAmounts: true
  userFolder: string
  userIdCreatorCompany: string
  userIdUpdatedatorCompany: string
  windowCodePageFiles: string
}
