export interface PayrollCompanyDetails {
  companyName?: any
  tabadulCompanyCode: string
  payrollDebitAccount: string
  currencyDebitAccount?: any
  payrollPrivilege?: any
  monthlyFee: number
  localBankFee: number
  fileFee?: any
  penaltyFee?: any
  profileNumber: string
  activeFlag?: any
  userFolder: string
  requestType?: any
  updateOnlyAmounts: boolean
  errorMessageKey?: any
  feedbackType?: any
  molEstbid?: any
  layout?: any
  payrollChargeAccount: string
  transactionFee: number
  transactionFailFee: number
  transactionCanFee: number
  transactionFeeLocal?: any
  transactionFailFeeLocal: number
  transactionCanFeeLocal: number
  postingFlag: string
  debitPreference: string
  fileAuth: string
  reject: string
  confirmation: string
  combined: string
  generationDate: number
  initial: string
  rejected: string
  combinedSum: string
  companyCat: string
  registered: boolean
}
