export const TransferLimitMock = {
  accountList: [
    {
      account15Length: 'string',
      account17Length: 'string',
      accountLevels: [true],
      accountPk: 0,
      alias: 'string',
      availableBalance: 0,
      availableSarBalance: 0,
      branchName: 'string',
      branchid: 'string',
      checkDigit: 'string',
      code000: 'string',
      companyPk: 0,
      currency: 'LKR',
      erNumber: 'string',
      exchangeRate: 0,
      fullAccountNumber: 'string',
      ibanNumber: 'string',
      inquiry: true,
      ledgerBalance: 0,
      modified: true,
      numberAccount: 'string',
      payment: true,
      status: 'string',
      txAccountString: 'string',
      typeAccount: 'string',
      typeFunction: 'string',
      unclearedBalance: 0,
    },
  ],
  accountListTo: [
    {
      account15Length: 'stringTo',
      account17Length: 'stringTo',
      accountLevels: [true],
      accountPk: 0,
      alias: 'string',
      availableBalance: 0,
      availableSarBalance: 0,
      branchName: 'string',
      branchid: 'string',
      checkDigit: 'string',
      code000: 'string',
      companyPk: 0,
      currency: 'AUD',
      erNumber: 'string',
      exchangeRate: 0,
      fullAccountNumber: 'string',
      ibanNumber: 'string',
      inquiry: true,
      ledgerBalance: 0,
      modified: true,
      numberAccount: 'string',
      payment: true,
      status: 'string',
      txAccountString: 'string',
      typeAccount: 'string',
      typeFunction: 'string',
      unclearedBalance: 0,
    },
  ],
  errorCode: 'string',
  errorDescription: 'string',
  errorResponse: {
    arabicMessage: 'string',
    code: 'string',
    description: 'string',
    englishMessage: 'string',
  },
  transferLimit: 200,
}
