export class Account {
    account15Length: string
    account17Length: string
    account21Length: string
    account18Length?: string
    accountLevels?: boolean[]
    accountPk?: number
    alias?: string
    availableBalance?: number
    availableSarBalance?: number
    branchName?: string
    branchid?: string
    ccdmAlias?: string
    checkDigit?: string
    code000?: string
    companyPk?: number
    currency?: string
    erNumber?: string
    exchangeRate?: number
    fullAccountNumber?: string
    ibanNumber?: string
    inquiry?: boolean
    ledgerBalance?: number
    modified?: boolean
    numberAccount?: string
    payment?: boolean
    status?: string
    txAccountString?: string
    typeAccount?: string
    typeFunction?: string
    unclearedBalance?: number
    dashboard?: boolean
}
