export class Company {
  branchPk: string
  branchId: string
  branchName: string
  branchNameEn: string
  branchRbs5: string
  branchLegacy5: string
  companyPk: number
  companyName: string
  status: string
  register: string
  profileNumber: string
  registrationDate: string
  lastBranchAdmin: string
  lastActionTimestamp: any
  expiryDate: string
  cicType: string
  userIdOp: string
  lastReturnCode: string
  lastLogonInfo: string
  newMessages: string
  dueBills: string
  civilianHijraExpiryDate: string
  transferLimit: number
  companyDetailsDTO: any
  institution: string
  institutionDe: string
  scription: string
  payrollCardsLayout: string
  payrollCardsInstitutionType: string
  payrollRegistered: string
  payrollFileSystem: string
  originatorId: string
  companyLimits: number
  directDebitAccount: string
  authenticationMethod: string
  tokenPrice: string
  changeAuthMethodDate: string
  organizationType: string
  etradeReferenceId: string
  samaId: string
  wpsPayrollRegistered: string
  wpsPayrollFileSystem: string
  wpsMolEstbid: string
  blockUnblockReason: string
  tokenMigrated: string
  numTokens: number
  numSTokenMigrations: number
  olpRequestId: string
  olpRegistered: string
  olpAccount: string
  payrollLayout: string
  companyCode: string
  companyCodeWps: string
  authDay: string
}
