/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthorizationResponseRecordWSDTO } from './authorizationResponseRecordWSDTO'
import { BatchSecurityDTO } from './batchSecurityDTO'
import { HostRequestDTO } from './hostRequestDTO'
import { ISessionInfo } from './iSessionInfo'
import { InitiationResponseRecordWSDTO } from './initiationResponseRecordWSDTO'

export interface BatchDTO {
  account18Length?: string
  account21Length?: string
  accountAlias?: string
  accountFromFk?: number
  accountNumber?: string
  amount?: number
  approvedBy?: string
  approvedDate?: string
  authorizationResponseRecordWSDTO?: AuthorizationResponseRecordWSDTO
  batchPk?: number
  cic?: string
  companyFk?: number
  futureSecurityLevelsDTOList?: Array<BatchSecurityDTO>
  futureStatus?: BatchDTO.FutureStatusEnum
  hostRequest?: HostRequestDTO
  initiatedBy?: string
  initiationDate?: string
  initiationResponseRecordWSDTO?: InitiationResponseRecordWSDTO
  max?: number
  nextStatus?: string
  offset?: number
  order?: string
  orderType?: string
  pdfSecurityLevelsDTOList?: Array<BatchSecurityDTO>
  rejectedReason?: string
  securityLevelsDTOList?: Array<BatchSecurityDTO>
  sessionInfo?: ISessionInfo
  status?: string
  type?: string
}
export namespace BatchDTO {
  export type FutureStatusEnum = 'NOT_ALLOWED' | 'PROCESS' | 'PENDING'
  export const FutureStatusEnum = {
    NOTALLOWED: 'NOT_ALLOWED' as FutureStatusEnum,
    PROCESS: 'PROCESS' as FutureStatusEnum,
    PENDING: 'PENDING' as FutureStatusEnum,
  }
}
