/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CompanyEmployeeDSO {
  account?: string
  accountFrom15length?: string
  bankCode?: string
  bankName?: string
  blockAmount?: string
  civilianId?: string
  companyPk?: number
  employeePk?: number
  employeeReference?: string
  kawadar?: string
  lastUpdate?: string
  name?: string
  processFlag?: string
  rajhiValidAccount?: boolean
  salary?: number
  status?: string
}
