/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CompanyBulkPaymentsParametersDTO } from './companyBulkPaymentsParametersDTO'
import { CompanyDetailsDTO } from './companyDetailsDTO'
import { CompanyHajjUmrahDTO } from './companyHajjUmrahDTO'
import { PrivilegeDTO } from './privilegeDTO'
import { VaCommissionProfilesDTO } from './vaCommissionProfilesDTO'

export interface CompanyDTO {
  authDay?: string
  authenticationMethod?: CompanyDTO.AuthenticationMethodEnum
  blockUnblockReason?: string
  branchId?: string
  branchLegacy5?: string
  branchName?: string
  branchNameEn?: string
  branchPk?: number
  branchRbs5?: string
  bulkPaymentsParameters?: CompanyBulkPaymentsParametersDTO
  bulkPaymentsRegistered?: boolean
  changeAuthMethodDate?: Date
  cicType?: string
  civilianHijraExpiryDate?: Date
  commissions?: Array<VaCommissionProfilesDTO>
  companyCode?: string
  companyCodeWps?: string
  companyDetailsDTO?: CompanyDetailsDTO
  companyHajjUmrah?: CompanyHajjUmrahDTO
  companyLimits?: number
  companyName?: string
  companyPk?: number
  directDebitAccount?: string
  dualAuthorization?: boolean
  dueBills?: string
  etradeReferenceId?: string
  expiryDate?: Date
  fees?: number
  institution?: string
  institutionDescription?: string
  lastActionTimestamp?: Date
  lastBranchAdmin?: string
  lastLogonInfo?: string
  lastReturnCode?: string
  lastUserLogin?: Date
  newMessages?: string
  numSTokenMigrations?: number
  numTokens?: number
  olpAccount?: string
  olpRegistered?: boolean
  olpRequestId?: string
  organizationType?: string
  originatorId?: string
  password?: string
  payrollCardsInstitutionType?: string
  payrollCardsLayout?: string
  payrollFileSystem?: boolean
  payrollLayout?: string
  payrollRegistered?: boolean
  privileges?: Array<PrivilegeDTO>
  profileNumber?: string
  register?: string
  registrationDate?: Date
  samaId?: string
  status?: string
  tokenMigrated?: string
  tokenPrice?: number
  transferLimit?: number
  userIdOp?: string
  vaClientId?: string
  wpsMolEstbid?: string
  wpsPayrollFileSystem?: boolean
  wpsPayrollRegistered?: boolean
}
export namespace CompanyDTO {
  export type AuthenticationMethodEnum = 'CHALLENGE' | 'OTP' | 'STATIC' | 'BOTH'
  export const AuthenticationMethodEnum = {
    CHALLENGE: 'CHALLENGE' as AuthenticationMethodEnum,
    OTP: 'OTP' as AuthenticationMethodEnum,
    STATIC: 'STATIC' as AuthenticationMethodEnum,
    BOTH: 'BOTH' as AuthenticationMethodEnum,
  }
}
