/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CompanyDetailsDTO {
  cicSponsor?: string
  customerName1?: string
  customerName2?: string
  customerType?: string
  documentNumber?: string
  email?: string
  expiryDate?: Date
  faxNumber?: string
  idNumber?: string
  issueDate?: Date
  issuePlace?: string
  juridicalState?: string
  language?: string
  nationalAddressFlag?: string
  phoneNumber?: string
  title?: string
}
