/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ISessionInfo } from './iSessionInfo'

export interface CompanyHajjUmrahDTO {
  bankCountry?: string
  companyFk?: number
  companyHajjPk?: number
  hajjRegistered?: string
  indexSelected?: number
  institution?: string
  institutionDescription?: string
  institutionType?: string
  layout?: string
  max?: number
  offset?: number
  order?: string
  orderType?: string
  selected?: boolean
  sessionInfo?: ISessionInfo
}
