/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BatchDTO } from './batchDTO'
import { CompanyDTO } from './companyDTO'

export interface HostRequestDTO {
  accountFrom?: string
  batchList?: Array<BatchDTO>
  companyDTO?: CompanyDTO
  fileName?: string
  fileReference?: string
  fileStatus?: string
  fileType?: string
  hostRequestsPk?: number
  newTransferDate?: string
  prepared?: boolean
  rejectionReason?: string
  requestDate?: string
  requestTime?: string
  transfaerDate?: string
  userFileName?: string
}
