/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PayrollFileHeaderDSO {
  accountFrom?: string
  batchName?: string
  dateType?: string
  fileReference?: string
  fileStatus?: string
  hostRequestPk?: number
  lastPaymentDate?: string
  numberOfPayments?: number
  rejectionReason?: string
  totalAmount?: number
  valueDate?: string
}
