/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PayrollDetailsDTO {
  account?: string
  accountFrom21length?: string
  amount?: number
  bankCode?: string
  blockAmount?: string
  employeeId?: string
  employeeNumber?: string
  employeeType?: string
  name?: string
  payrollDetailsPk?: number
  processFlag?: string
}
