/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PayrollParametersDSO {
  activeFlag?: string
  combined?: string
  combinedSum?: string
  companyCat?: string
  companyName?: string
  confirmation?: string
  currencyDebitAccount?: string
  debitPreference?: string
  errorMessageKey?: string
  feedbackType?: string
  fileAuth?: string
  fileFee?: number
  generationDate?: number
  initial?: string
  layout?: string
  localBankFee?: number
  molEstbid?: string
  monthlyFee?: number
  payrollChargeAccount?: string
  payrollDebitAccount?: string
  payrollPrivilege?: string
  penaltyFee?: number
  postingFlag?: string
  profileNumber?: string
  registered?: boolean
  reject?: string
  rejected?: string
  requestType?: string
  tabadulCompanyCode?: string
  transactionCanFee?: number
  transactionCanFeeLocal?: number
  transactionFailFee?: number
  transactionFailFeeLocal?: number
  transactionFee?: number
  transactionFeeLocal?: number
  updateOnlyAmounts?: boolean
  userFolder?: string
  vatFileFee?: number
  vatMonthlyFee?: number
  vatPenaltyFee?: number
  vatTransactionFee?: number
  vatTransactionFeeLocal?: number
}
