/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RequestGetMOLFilesPayrollWPS {
  amountfrom?: number
  amountto?: number
  batchName?: string
  customerReference?: string
  debitAccount?: string
  fileType?: string
  initiationDatefrom?: Date
  initiationDateto?: Date
  /**
   * Num Page
   */
  page: number
  paymentDatefrom?: Date
  paymentDateto?: Date
  /**
   * Num Rows for Page
   */
  rows: number
  search?: boolean
  systemFileName?: string
}
