/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ErrorServiceResponse } from './errorServiceResponse'
import { PayrollParametersDSO } from './payrollParametersDSO'
import { ResponseGenerateChallenge } from 'app/Application/Model/responsegeneratechallenge.type'
import { WPSCompanyEmployeeDSO } from './wPSCompanyEmployeeDSO'
import { WPSPayrollSalaryPaymentBatchDSO } from './wPSPayrollSalaryPaymentBatchDSO'
import { WPSSalaryPaymentDetailsDSO } from './wPSSalaryPaymentDetailsDSO'

export interface ResponsePayrollWPSPendingSalaryValidate {
  errorCode?: string
  errorDescription?: string
  errorResponse?: ErrorServiceResponse
  errors?: Array<string>
  generateChallengeAndOTP?: ResponseGenerateChallenge
  paymentDateMinus1?: Date
  payrollCompanyDetails?: PayrollParametersDSO
  payrollSalaryPaymentBatch?: WPSPayrollSalaryPaymentBatchDSO
  salaryPaymentDetails?: WPSSalaryPaymentDetailsDSO
  selectedEmployeeList?: Array<WPSCompanyEmployeeDSO>
  todayDateSanitized?: Date
  valueDateTooClose?: boolean
}
