/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BatchListsContainerWPSPayrollFileUploadBatchDSO } from './batchListsContainerWPSPayrollFileUploadBatchDSO'
import { ErrorServiceResponse } from './errorServiceResponse'
import { Maplongstring } from './maplongstring'
import { ResponseGenerateChallenge } from 'app/Application/Model/responsegeneratechallenge.type'
import { WPSSalaryPaymentDetailsDSO } from './wPSSalaryPaymentDetailsDSO'

export interface ResponsePayrollWPSPendingFileValidate {
  batchList?: BatchListsContainerWPSPayrollFileUploadBatchDSO
  errorCode?: string
  errorDescription?: string
  errorResponse?: ErrorServiceResponse
  errors?: Array<Maplongstring>
  generateChallengeAndOTP?: ResponseGenerateChallenge
  salaryPaymentDetails?: WPSSalaryPaymentDetailsDSO
}
