/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DetailsFilePayrollPWPS } from './detailsFilePayrollPWPS'
import { ErrorServiceResponse } from './errorServiceResponse'
import { ResponseGenerateChallenge } from 'app/Application/Model/responsegeneratechallenge.type'
import { WPSSalaryFileDSO } from './wPSSalaryFileDSO'

export interface ResponseSelectViewProcessedFilePayrollWPS {
  details?: DetailsFilePayrollPWPS
  errorCode?: string
  errorDescription?: string
  errorResponse?: ErrorServiceResponse
  generateChallengeAndOTP?: ResponseGenerateChallenge
  oldFile?: boolean
  paid?: number
  paidAmount?: number
  salaryFileDetails?: WPSSalaryFileDSO
  unpaid?: number
  unpaidAmount?: number
}
