/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ErrorServiceResponse } from './errorServiceResponse'
import { LineValidationDTO } from './lineValidationDTO'
import { ResponseGenerateChallenge } from 'app/Application/Model/responsegeneratechallenge.type'
import { WPSCompanyEmployeeDSO } from './wPSCompanyEmployeeDSO'
import { WPSPayrollBatchDSO } from './wPSPayrollBatchDSO'
import { WPSSalaryFileDSO } from './wPSSalaryFileDSO'
import { WPSSalaryPaymentDetailsDSO } from './wPSSalaryPaymentDetailsDSO'

export interface ResponseValidateFileSalaryPaymentsPayrollWPS {
  companyEmployeeList?: Array<WPSCompanyEmployeeDSO>
  errorCode?: string
  errorDescription?: string
  errorResponse?: ErrorServiceResponse
  fileName?: string
  files?: Array<WPSSalaryFileDSO>
  generateChallengeAndOTP?: ResponseGenerateChallenge
  lineValidationList?: Array<LineValidationDTO>
  linesWithError?: number
  payrollBatch?: WPSPayrollBatchDSO
  salaryPaymentDetails?: WPSSalaryPaymentDetailsDSO
  validBalance?: number
}
