/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchSecurityDTO } from './batchSecurityDTO'
import { InitiationResponseRecordWSDTO } from './initiationResponseRecordWSDTO'
import { Account } from 'app/Application/Model/account'

export interface SalaryPaymentDetailsDTO {
  account?: Account
  activeFlag?: string
  approvedDate?: Date
  batchName?: string
  batchStatus?: string
  combined?: string
  combinedSum?: string
  companyCat?: string
  companyName?: string
  confirmation?: string
  currencyDebitAccount?: string
  customerReference?: string
  debitAccountFrom21length?: string
  debitPreference?: string
  errorMessageKey?: string
  feedbackType?: string
  fileAuth?: string
  fileFee?: number
  fileReference?: string
  futureSecurityLevelsDTOList?: Array<BatchSecurityDTO>
  generationDate?: number
  initial?: string
  initiationDate?: Date
  initiationResponseRecordWSDTO?: InitiationResponseRecordWSDTO
  layout?: string
  localBankFee?: number
  molEstbid?: string
  monthlyFee?: number
  numEmployees?: number
  numNonRajhiTransfers?: number
  numRajhiTransfers?: number
  organizationType?: string
  paymentDate?: Date
  paymentPurpose?: string
  payrollChargeAccount?: string
  payrollDebitAccount?: string
  payrollPrivilege?: string
  penaltyFee?: number
  postingFlag?: string
  profileNumber?: string
  registered?: boolean
  reject?: string
  rejected?: string
  remarks?: string
  requestType?: string
  tabadulCompanyCode?: string
  totalAmount?: number
  totalCancellationCharges?: number
  totalEstimated?: number
  totalFeesNonRajhi?: number
  totalFeesRajhi?: number
  totalNumNonRajhi?: number
  totalNumRajhi?: number
  transactionCanFee?: number
  transactionCanFeeLocal?: number
  transactionFailFee?: number
  transactionFailFeeLocal?: number
  transactionFee?: number
  transactionFeeLocal?: number
  updateOnlyAmounts?: boolean
  userFolder?: string
  vatFileFee?: number
  vatMonthlyFee?: number
  vatPenaltyFee?: number
  vatTransactionFee?: number
  vatTransactionFeeLocal?: number
}
