/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SalaryFileHeaderDTO {
  accountFrom?: string
  all?: string
  billHeader?: string
  channelId?: string
  companyRemarks?: string
  customerReference?: string
  dateSend?: string
  dateValue?: string
  emptyInfo?: string
  keyHeader?: string
  messageCode?: string
  paymentPurpose?: string
  sequence?: string
  systemHeaderRef?: string
  totalAmount?: string
  totalCnt?: string
  type?: string
}
