/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface WPSCompanyEmployeeDSO {
  account?: string
  accountFrom15length?: string
  accountOLD?: string
  allowanceHousing?: number
  allowanceOther?: number
  bankBranchCode?: string
  bankBranchName?: string
  bankCode?: string
  bankName?: string
  blockAmount?: string
  civilianId?: string
  civilianIdOLD?: string
  companyPk?: number
  currencyCode?: string
  currencyName?: string
  deductions?: number
  departmentId?: string
  employeePk?: number
  employeeReference?: string
  employeeReferenceOLD?: string
  kawadar?: string
  lastUpdate?: string
  name?: string
  payMode?: string
  paymentDetails?: string
  processFlag?: string
  rajhiValidAccount?: boolean
  remarks?: string
  salary?: number
  salaryBasic?: number
  salaryCompositionValid?: boolean
  status?: string
}
