/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface WPSPayrollEmployeeHeaderDetailsDSO {
  accountFrom?: string
  chanelId?: string
  coProf?: string
  companyRemakrs?: string
  currencyCode?: string
  dateSend?: string
  emptyInfo?: string
  fileParam?: string
  fileReference?: string
  filler?: string
  keyHeader?: string
  molId?: string
  originalLine?: string
  paymentPurpose?: string
  sequence?: string
  status?: WPSPayrollEmployeeHeaderDetailsDSO.StatusEnum
  systemHeaderRef?: string
  totalAmount?: number
  totalEmployees?: number
  type?: string
  valueDate?: string
}
export namespace WPSPayrollEmployeeHeaderDetailsDSO {
  export type StatusEnum = 'NOT_ALLOWED' | 'PROCESS' | 'PENDING'
  export const StatusEnum = {
    NOTALLOWED: 'NOT_ALLOWED' as StatusEnum,
    PROCESS: 'PROCESS' as StatusEnum,
    PENDING: 'PENDING' as StatusEnum,
  }
}
