/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface WPSSalaryFileDetailsDTO {
  account?: string
  accountFrom21length?: string
  allowanceHousing?: number
  allowanceOther?: number
  amount?: number
  bankBranchCode?: string
  bankBranchName?: string
  bankCode?: string
  blockAmount?: string
  checkDigit?: string
  currencyCode?: string
  deductions?: number
  department?: string
  employeeId?: string
  employeeNumber?: string
  employeeType?: string
  messageCode?: string
  messageDescription?: string
  name?: string
  originalLine?: string
  payMode?: string
  paymentDetails?: string
  payrollDetailsPk?: number
  processFlag?: string
  remarks?: string
  salaryBasic?: number
  systemHeaderRef?: string
}
