import { HttpClient, HttpParams, HttpResponse } from '@angular/common/http'
import { Injectable } from '@angular/core'
import { Observable, throwError as observableThrowError } from 'rxjs'
import { catchError, map } from 'rxjs/operators'
import { ConfigResourceService } from '../../../../../../core/config/config.resource.local'
import { DateFormatPipe } from '../../../../../Components/common/Pipes/date-format-pipe'
import { Exception } from '../../../../../Model/exception'

@Injectable()
export class RequestReactivateService {
  servicesUrl: string
  dateFormat = 'yyyy-MM-dd'

  servicesConfig = {
    services: {
      '158': {
        name: 'payments.moiPayments.civilDefense.civilDefense',
        url: '/moiPayment/requestStatus/civilDefenseViolationInitiate',
        applicationTypes: {
          '055': {
            name: 'payments.moiPayments.civilDefense.payAllCivilDefense',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: true,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '056': {
            name: 'payments.moiPayments.civilDefense.payOneCivilDefense',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: true,
            violationId: false,
            violatorId: true,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
        },
      },
      '096': {
        name: 'payments.moiPayments.civilRegistrationServices.civilServices',
        url: '/moiPayment/requestStatus/civilRegistrationInitiate',
        applicationTypes: {
          '017': {
            name: 'payments.moiPayments.civilRegistrationServices.birthRegistration',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: true,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: true,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '018': {
            name: 'payments.moiPayments.civilRegistrationServices.deathRegistration',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: true,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: true,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '020': {
            name: 'payments.moiPayments.civilRegistrationServices.divorceRegistration',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: true,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: true,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '053': {
            name: 'payments.moiPayments.civilRegistrationServices.issueFamilyCard',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: true,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: true,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: true,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '021': {
            name: 'payments.moiPayments.civilRegistrationServices.issueIdCard',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: true,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: true,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: true,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '019': {
            name: 'payments.moiPayments.civilRegistrationServices.marriageRegistration',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: true,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: true,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '096': {
            name: 'payments.moiPayments.civilRegistrationServices.otherFeesAndFines',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: true,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
        },
      },
      '091': {
        name: 'payments.moiPayments.drivingLicense.drivingLicenseServices',
        url: '/moiPayment/requestStatus/drivingLicenseInitiate',
        applicationTypes: {
          '022': {
            name: 'payments.moiPayments.drivingLicense.issueLicense',
            associatedBorderNumber: false,
            beneficiaryId: true,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: true,
            licenseType: true,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '023': {
            name: 'payments.moiPayments.drivingLicense.issueLicenseFromOld',
            associatedBorderNumber: false,
            beneficiaryId: true,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: true,
            licenseType: true,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '025': {
            name: 'payments.moiPayments.drivingLicenseServices.renewLicense',
            associatedBorderNumber: false,
            beneficiaryId: true,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: true,
            licenseType: true,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '024': {
            name: 'payments.moiPayments.drivingLicenseServices.replaceLicense',
            associatedBorderNumber: false,
            beneficiaryId: true,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: true,
            licenseType: true,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
        },
      },
      '090': {
        name: 'payments.moiPayments.expatriateServices.expatriateServices',
        url: '/moiPayment/requestStatus/alienControlInitiate',
        applicationTypes: {
          '014': {
            name: 'payments.moiPayments.expatriateServices.addingDependentBornInsideSaudiArabia',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: true,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '058': {
            name: 'payments.moiPayments.expatriateServices.associateFees',
            associatedBorderNumber: true,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: true,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '059': {
            name: 'payments.moiPayments.expatriateServices.associateFeesForAll',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: true,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '012': {
            name: 'payments.moiPayments.expatriateServices.changeOccupation',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '013': {
            name: 'payments.moiPayments.expatriateServices.dependantsEntryVisaFeeCollection',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: true,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: true,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '015': {
            name: 'payments.moiPayments.expatriateServices.dependentSeparation',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '005': {
            name: 'payments.moiPayments.expatriateServices.exitReEntryVisaMultiple',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: true,
            visaNumber: false,
            visaType: false,
          },

          '004': {
            name: 'payments.moiPayments.expatriateServices.exitReEntryVisaSingle',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: true,
            visaNumber: false,
            visaType: false,
          },

          '057': {
            name: 'payments.moiPayments.expatriateServices.extendExitReEntryVisaDuration',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: true,
            visaNumber: true,
            visaType: false,
          },

          '001': {
            name: 'payments.moiPayments.expatriateServices.extendVisitorVisa',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: true,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '002': {
            name: 'payments.moiPayments.expatriateServices.issueNewIqamah',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: true,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: true,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: true,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: true,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '016': {
            name: 'payments.moiPayments.expatriateServices.issueNewIqamahCitizensWife',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: true,
            cardVersionNumber: false,
            citizenId: true,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: true,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '052': {
            name: 'payments.moiPayments.expatriateServices.lostPassportFine',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '003': {
            name: 'payments.moiPayments.expatriateServices.renewIqamah',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: true,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '008': {
            name: 'payments.moiPayments.expatriateServices.replaceIqamah',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '009': {
            name: 'payments.moiPayments.expatriateServices.transferDependantHeadHousehold',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: true,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: true,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: true,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '011': {
            name: 'payments.moiPayments.expatriateServices.transferDependantNewHeadHousehold',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '010': {
            name: 'payments.moiPayments.expatriateServices.transferHeadHouseholdDependant',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '038': {
            name: 'payments.moiPayments.expatriateServices.transferOfSponsorship',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },

          '006': {
            name: 'payments.moiPayments.expatriateServices.visaCancellation',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: true,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: true,
            visaType: false,
          },
        },
      },
      '092': {
        name: 'payments.moiPayments.payments.saudiPassServices',
        url: '/moiPayment/requestStatus/saudiPassportsInitiate',
        applicationTypes: {
          '035': {
            name: 'payments.moiPayments.payments.issueNewPass',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: true,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: true,
            passportType: true,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '036': {
            name: 'payments.moiPayments.saudiPassportServices.reIssuePassport',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: true,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: true,
            passportType: true,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '037': {
            name: 'payments.moiPayments.payments.renewPass',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: true,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: true,
            passportType: true,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
        },
      },
      '093': {
        name: 'payments.moiPayments.trafficViolations.trafficViolations',
        url: '/moiPayment/requestStatus/trafficViolationInitiate',
        applicationTypes: {
          '040': {
            name: 'payments.moiPayments.trafficViolations.queryTrafficViolation',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: true,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '041': {
            name: 'payments.moiPayments.trafficViolations.queryViolationsById',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: true,
            violatorId: true,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
        },
      },
      '094': {
        name: 'payments.moiPayments.vehicleRegistrationServices.vehicleRegistrationServices',
        url: '/moiPayment/requestStatus/motorVehiclesInitiate',
        applicationTypes: {
          '031': {
            name: 'payments.moiPayments.vehicleRegistrationServices.exchangePlates',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: true,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: true,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '032': {
            name: 'payments.moiPayments.vehicleRegistrationServices.exchangePlatesNotByOwner',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: true,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: true,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: true,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '030': {
            name: 'payments.moiPayments.vehicleRegistrationServices.exportVehicle',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: true,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: true,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '042': {
            name: 'payments.moiPayments.vehicleRegistrationServices.registerVehicle',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: true,
            newVehicleRegistrationType: true,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: true,
            vehicleCustomCardNumber: true,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '043': {
            name: 'payments.moiPayments.vehicleRegistrationServices.reImportVehicle',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: true,
            newVehicleRegistrationType: true,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: true,
            vehicleCustomCardNumber: true,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '029': {
            name: 'payments.moiPayments.vehicleRegistrationServices.reIssueLicensePlate',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: true,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: true,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '028': {
            name: 'payments.moiPayments.vehicleRegistrationServices.reIssueRegistrationCard',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: true,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: true,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '026': {
            name: 'payments.moiPayments.vehicleRegistrationServices.renewVehicleRegistration',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: true,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: true,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '027': {
            name: 'payments.moiPayments.vehicleRegistrationServices.transferOwner',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: true,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: true,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: true,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '045': {
            name: 'payments.moiPayments.vehicleRegistrationServices.transferPlatesChangingCurrent',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: true,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: true,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: true,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: true,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '044': {
            name: 'payments.moiPayments.vehicleRegistrationServices.transferPlatesGivePlates',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: true,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: true,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: true,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: true,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
        },
      },
      '095': {
        name: 'payments.moiPayments.payments.visaServices',
        url: '/moiPayment/requestStatus/visaInitiate',
        applicationTypes: {
          '038': {
            name: 'payments.moiPayments.payments.familyVisa',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: true,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: true,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
          },
          '039': {
            name: 'payments.moiPayments.payments.laborVisa',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: true,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: true,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            violatorId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: true,
          },
        },
      },
      '126': {
        name: 'payments.moiPayments.payments.publicViolation',
        url: '/moiPayment/requestStatus/publicViolationInitiate',
        applicationTypes: {
          '060': {
            name: 'payments.moiPayments.publicViolation.publicViolation',
            associatedBorderNumber: false,
            beneficiaryId: false,
            birthDate: false,
            borderNumber: false,
            cardVersionNumber: false,
            citizenId: false,
            currentOwnerId: false,
            deathDate: false,
            divorceDate: false,
            feesDurationEndDate: false,
            householdIdNumber: false,
            iqamaDuration: false,
            iqamaId: false,
            issuanceReason: false,
            jobCategory: false,
            licenseDuration: false,
            licenseType: false,
            nationalIdNumber: false,
            newOwnerId: false,
            newVehicleRegistrationType: false,
            numberDependant: false,
            numberOfVisas: false,
            marriageDate: false,
            passportDuration: false,
            passportType: false,
            sponsorId: false,
            vehicleBodyType: false,
            vehicleCustomCardNumber: false,
            vehicleSequenceNumber: false,
            veredictNumber: false,
            violationId: false,
            visaDuration: false,
            visaNumber: false,
            visaType: false,
            violatorId: true,
            issuingEntity: true,
            category: true,
          },
        },
      },
    },
    fieldLabels: {
      associatedBorderNumber: 'eGovernment.associatedBorderNumber',
      beneficiaryId: 'eGovernment.beneficiaryId',
      birthDate: 'eGovernment.birthDate',
      borderNumber: 'eGovernment.borderNumber',
      cardVersionNumber: 'eGovernment.cardVersionNumber',
      citizenId: 'eGovernment.citizenId',
      currentOwnerId: 'eGovernment.currentOwnerId',
      deathDate: 'eGovernment.deathDate',
      divorceDate: 'eGovernment.divorceDate',
      feesDurationEndDate: 'eGovernment.feesDurationEndDate',
      householdIdNumber: 'eGovernment.householdIdNumber',
      iqamaDuration: 'eGovernment.iqamaDuration',
      iqamaId: 'eGovernment.iqamaId',
      issuanceReason: 'eGovernment.issuanceReason',
      jobCategory: 'eGovernment.jobCategory',
      licenseDuration: 'eGovernment.licenseDuration',
      licenseType: 'eGovernment.licenseType',
      nationalIdNumber: 'eGovernment.nationalIdNumber',
      newOwnerId: 'eGovernment.newOwnerId',
      newVehicleRegistrationType: 'eGovernment.newVehicleRegistrationType',
      numberDependant: 'eGovernment.numberDependant',
      numberOfVisas: 'eGovernment.numberOfVisas',
      marriageDate: 'eGovernment.marriageDate',
      passportDuration: 'eGovernment.passportDuration',
      passportType: 'eGovernment.passportType',
      sponsorId: 'eGovernment.sponsorId',
      vehicleBodyType: 'eGovernment.vehicleBodyType',
      vehicleCustomCardNumber: 'eGovernment.vehicleCustomCardNumber',
      vehicleSequenceNumber: 'eGovernment.vehicleSequenceNumber',
      veredictNumber: 'eGovernment.veredictNumber',
      violationId: 'eGovernment.violationId',
      violatorId: 'eGovernment.violatorId',
      visaDuration: 'eGovernment.visaDuration',
      visaNumber: 'eGovernment.visaNumber',
      visaType: 'eGovernment.visaType',
      issuingEntity: 'eGovernment.issuingEntity',
      category: 'eGovernment.category',
    },
    /*
CivilDefenseService: "158",
CivilService: "096",
DrivingLicenseService: "091",
ExpatriateService: "090",
SaudiPassportServices: "092",
TrafficServices: "093",
VehicleRegistrationServices: "094",
VisaServices: "095",
PublicViolation: "126",
 */
    /*
        subService: {
            CivilDefenseAll: "055",
            CivilDefenseOne: "056",
            BirthRegistration: "017",
            DeathRegistration: "018",
            DivorceRegistration: "020",
            IssueFamilyCard: "053",
            IssueIdCard: "021",
            MarriageRegistration: "019",
            OtherFeesandFines: "096",
            DrivingLicenseServices: "022",
            IssueLicenseFromOldLicense: "023",
            RenewLicense: "025",
            ReplaceLicense: "024",
            AddingDependentBornInsideSaudiArabiaAfterOneYearFromHisDateOfBirth: "014",
            AssociateFeesForASpecificAssociate: "058",
            AssociateFeesforAllRegisteredAssociatesOnTheHeadOfHouseholdIqama: "059",
            ChangeOfOccupation: "012",
            DependantsEntryVisaFeeCollection: "013",
            DependentSeparation: "015",
            ExitReEntryVisaMultiple: "005",
            ExitReEntryVisaSingle: "004",
            ExtendExitReEntryVisaDuration: "057",
            ExtendVisitorVisa: "001",
            IssueNewIqamah: "002",
            IssueNewIqamahForACitizensWife: "016",
            LostPassportFine: "052",
            RenewIquamah: "003",
            ReplaceIquamah: "008",
            TransferDependantToBeHeadOfHousehold: "009",
            TransferDependantToANewHeadOfHousehold: "011",
            TransferHeadOfHouseholdToBeDependant: "010",
            TransferOfSponsorship: "038",
            VisaCancellation: "006",
            IssueNewPassport: "035",
            ReIssuePassport: "036",
            RenewPassport: "037",
            QueryTrafficViolation: "040",
            QueryViolationById: "041",
            ExchangePlates: "031",
            ExchangePlatesNotByOwner: "032",
            ExportVehicle: "030",
            RegisterVehicle: "042",
            ReImportVehicle: "043",
            ReIssueLicensePlate: "029",
            ReIssueRegistrationCard: "028",
            RenewVehicleRegistration: "026",
            TransferOwner: "027",
            TransferPlatesChangingCurrentVehiclePlate: "045",
            TransferPlatesGivePlatesToRegiteredVehicleWithoutPlates: "044",
            FamilyVisa: "038",
            LaborVisa: "039",
            PayByViolatorIdForASpecificCategory: "60"
        },
         */
  }

  constructor(
    private http: HttpClient,
    public config: ConfigResourceService,
    private dateFormatPipe: DateFormatPipe,
  ) {
    this.servicesUrl = config.getServicesUrl()
  }

  public handleError(error: HttpResponse<any> | any) {
    // In a real world app, you might use a remote logging infrastructure
    let errMsg: string
    if (error instanceof HttpResponse) {
      const err = error['error'] || JSON.stringify(error)
      errMsg = `${error.status} - ${error.statusText || ''} ${err}`
    } else {
      errMsg = error.message ? error.message : error.toString()
    }
    console.error(errMsg)
    const errorService: Exception = new Exception('handle', errMsg)
    return observableThrowError(errorService)
  }

  public reInitiate(batch): Observable<any> {
    const data = this.remapValues(batch)

    return this.http
      .post(
        this.servicesUrl + this.servicesConfig.services[batch.serviceType].url,
        data,
      )
      .pipe(
        map((response: any) => {
          const body = response
          if (response.errorCode !== '0') {
            const exception: Exception = new Exception(
              body.errorCode,
              body.errorDescription,
            )
            return exception
          } else {
            const output = body
            return output
          }
        }),
        catchError(this.handleError),
      )
  }

  public save(id, batch, requestValidate): Observable<any> {
    const data = {
      batchPk: id,
      eGovSadadBatch: batch,
      requestValidate,
    }

    return this.http
      .post(this.servicesUrl + '/moiPayment/requestStatus/confirm', data)
      .pipe(
        map((response: any) => {
          const body = response
          if (response.errorCode !== '0') {
            const exception: Exception = new Exception(
              body.errorCode,
              body.errorDescription,
              body.generateChallengeAndOTP,
            )
            return exception
          } else {
            return body
          }
        }),
        catchError(this.handleError),
      )
  }

  public delete(batch): Observable<any> {
    const data = {
      batch,
    }

    let _param: HttpParams = new HttpParams()
    _param = _param.append('deletebody', JSON.stringify(data))

    return this.http
      .delete(this.servicesUrl + '/moiPayment/requestStatus/delete', {
        params: _param,
      })
      .pipe(
        map((response: any) => {
          const body = response
          if (response.errorCode !== '0') {
            const exception: Exception = new Exception(
              body.errorCode,
              body.errorDescription,
            )
            return exception
          } else {
            return body
          }
        }),
        catchError(this.handleError),
      )
  }

  getServicesConfig() {
    return this.servicesConfig
  }

  getLabelValueFromBatch(batch, label) {
    // tslint:disable-next-line:prefer-for-of
    for (let i = 0; i < batch.details.length; i++) {
      if (batch.details[i].labelKey == label) {
        return batch.details[i].value
      }
    }
  }

  remapValues(batch) {
    const data = {
      accountNumber: batch.accountNumber ? batch.accountNumber : null,
      applicationType: batch.applicationType ? batch.applicationType : null,
      serviceType: batch.serviceType ? batch.serviceType : null,
      transactionType: batch.transactionType ? batch.transactionType : null,
    }

    const applicationsConfig =
      this.servicesConfig.services[batch.serviceType].applicationTypes[
        batch.applicationType
      ]

    const applicationsConfigKeys = Object.keys(applicationsConfig)

    applicationsConfigKeys.forEach((fieldKey) => {
      if (applicationsConfig[fieldKey] === true) {
        if (
          fieldKey === 'birthDate' ||
          fieldKey === 'deathDate' ||
          fieldKey === 'divorceDate' ||
          fieldKey === 'feesDurationEndDate' ||
          fieldKey === 'marriageDate'
        ) {
          data['day'] = batch[fieldKey]['day']
            ? '' + batch[fieldKey]['day']
            : null
          data['month'] = batch[fieldKey]['month']
            ? '' + batch[fieldKey]['month']
            : null
          data['year'] = batch[fieldKey]['year']
            ? '' + batch[fieldKey]['year']
            : null
        } else {
          data[fieldKey] = batch[fieldKey] ? batch[fieldKey] : null
        }
      }
    })

    return data
  }

  getDataToSend(batch) {
    const data = {
      accountNumber: batch.accountNumber,
      applicationType: batch.applicationType,
      serviceType: batch.serviceType,
      transactionType: batch.transactionType,
      paymentId: batch.paymentId,
    }

    const applicationsConfig =
      this.servicesConfig.services[batch.serviceType].applicationTypes[
        batch.applicationType
      ]

    const applicationsConfigKeys = Object.keys(applicationsConfig)

    applicationsConfigKeys.forEach((fieldKey) => {
      if (applicationsConfig[fieldKey] === true) {
        if (
          fieldKey === 'birthDate' ||
          fieldKey === 'deathDate' ||
          fieldKey === 'divorceDate' ||
          fieldKey === 'feesDurationEndDate' ||
          fieldKey === 'marriageDate'
        ) {
          const tmpDate = this.getLabelValueFromBatch(
            batch,
            this.servicesConfig.fieldLabels[fieldKey],
          )
          if (tmpDate) {
            const date = tmpDate.split('.')
            data[fieldKey] = {
              day: +date[0],
              month: +date[1],
              year: +date[2],
            }
          }
        } else {
          data[fieldKey] = this.getLabelValueFromBatch(
            batch,
            this.servicesConfig.fieldLabels[fieldKey],
          )
        }
      }
    })
    //
    return data
  }
}
