// tslint:disable-next-line: no-unused-expression
;`
{
    "errorCode": "0",
    "errorDescription": "",
    "errorResponse": {
        "englishMessage": "",
        "arabicMessage": "",
        "code": "",
        "description": ""
    },
    "months": [
        "'September2017'",
        "'October2017'",
        "'November2017'",
        "'December2017'",
        "'February2018'"
    ],
    "files": [
        {
            "fileName": "05000_20161011_01",
            "batchName": "BatchName1",
            "userFileName": null,
            "dataReceived": "2017-09-12",
            "dirUploadArchive": null,
            "fileSize": 0,
            "type": null,
            "salaryFileHeaderDTO": null,
            "salaryDetailsDTOList": null,
            "path": null,
            "rajhiRecordCount": 0,
            "rajhiRecordAmount": 0,
            "localRecordCount": 1,
            "localRecordAmount": 100,
            "paymentDate": "2017-09-13",
            "initiationDate": "2017-09-12",
            "totalAmount": 100,
            "accountFrom": "040330010006080010223",
            "customerReference": "CRBN1",
            "paid": null,
            "unPaid": null,
            "numPaid": 0,
            "numUnPaid": 0,
            "initiatedBy": "usertest",
            "approvedDate": "2017-09-12",
            "approvedBy": "usertest",
            "cancelled": null,
            "batchPk": null,
            "companyCode": null,
            "fileHash": null,
            "paymentPurpose": null,
            "molEstbid": null,
            "wpsSalaryDetailsDTOList": null
        },
        {
            "fileName": "00000147_W_20171018_01",
            "batchName": "test",
            "userFileName": null,
            "dataReceived": "2017-10-17",
            "dirUploadArchive": null,
            "fileSize": 0,
            "type": null,
            "salaryFileHeaderDTO": null,
            "salaryDetailsDTOList": null,
            "path": null,
            "rajhiRecordCount": 0,
            "rajhiRecordAmount": 0,
            "localRecordCount": 8,
            "localRecordAmount": 8,
            "paymentDate": "2017-10-18",
            "initiationDate": "2017-10-17",
            "totalAmount": 2,
            "accountFrom": "040330010006080010223",
            "customerReference": "2017101708594301",
            "paid": null,
            "unPaid": null,
            "numPaid": 0,
            "numUnPaid": 0,
            "initiatedBy": "usertest",
            "approvedDate": "2017-10-17",
            "approvedBy": "usertest",
            "cancelled": null,
            "batchPk": null,
            "companyCode": null,
            "fileHash": null,
            "paymentPurpose": null,
            "molEstbid": null,
            "wpsSalaryDetailsDTOList": null
        },
        {
            "fileName": "00000147_W_20171126_01",
            "batchName": "tet",
            "userFileName": null,
            "dataReceived": "2017-11-20",
            "dirUploadArchive": null,
            "fileSize": 0,
            "type": null,
            "salaryFileHeaderDTO": null,
            "salaryDetailsDTOList": null,
            "path": null,
            "rajhiRecordCount": 2,
            "rajhiRecordAmount": 21378,
            "localRecordCount": 0,
            "localRecordAmount": 0,
            "paymentDate": "2017-11-26",
            "initiationDate": "2017-11-20",
            "totalAmount": 21378,
            "accountFrom": "040330010006080010223",
            "customerReference": "2017102513281901",
            "paid": null,
            "unPaid": null,
            "numPaid": 0,
            "numUnPaid": 0,
            "initiatedBy": "usertest",
            "approvedDate": "2017-11-20",
            "approvedBy": "usertest",
            "cancelled": null,
            "batchPk": null,
            "companyCode": null,
            "fileHash": null,
            "paymentPurpose": null,
            "molEstbid": null,
            "wpsSalaryDetailsDTOList": null
        },
        {
            "fileName": "00000147_W_20171203_01",
            "batchName": "klj",
            "userFileName": null,
            "dataReceived": "2017-12-01",
            "dirUploadArchive": null,
            "fileSize": 0,
            "type": null,
            "salaryFileHeaderDTO": null,
            "salaryDetailsDTOList": null,
            "path": null,
            "rajhiRecordCount": 8,
            "rajhiRecordAmount": 2505,
            "localRecordCount": 0,
            "localRecordAmount": 0,
            "paymentDate": "2017-12-03",
            "initiationDate": "2017-12-01",
            "totalAmount": 1,
            "accountFrom": "114000010006080013335",
            "customerReference": "kjkkj",
            "paid": null,
            "unPaid": null,
            "numPaid": 0,
            "numUnPaid": 0,
            "initiatedBy": "usertest",
            "approvedDate": "2017-12-01",
            "approvedBy": "usertest",
            "cancelled": null,
            "batchPk": null,
            "companyCode": null,
            "fileHash": null,
            "paymentPurpose": null,
            "molEstbid": null,
            "wpsSalaryDetailsDTOList": null
        },
        {
            "fileName": "00000147_W_20180222_01",
            "batchName": "uuuuuuuuuuuuuuuuu",
            "userFileName": null,
            "dataReceived": "2017-12-01",
            "dirUploadArchive": null,
            "fileSize": 0,
            "type": null,
            "salaryFileHeaderDTO": null,
            "salaryDetailsDTOList": null,
            "path": null,
            "rajhiRecordCount": 5,
            "rajhiRecordAmount": 1001.02,
            "localRecordCount": 0,
            "localRecordAmount": 0,
            "paymentDate": "2018-02-22",
            "initiationDate": "2017-12-01",
            "totalAmount": 501,
            "accountFrom": "114000010006080013335",
            "customerReference": "uuuuuuuuuuuuu",
            "paid": null,
            "unPaid": null,
            "numPaid": 0,
            "numUnPaid": 0,
            "initiatedBy": "usertest",
            "approvedDate": "2018-02-20",
            "approvedBy": "usertest",
            "cancelled": null,
            "batchPk": null,
            "companyCode": null,
            "fileHash": null,
            "paymentPurpose": null,
            "molEstbid": null,
            "wpsSalaryDetailsDTOList": null
        }
    ]
}
`
